Importações

In [2]:
import time
import scipy.linalg as sp
import numpy as np
import sympy as sym
from math import *


Exemplo teste

In [114]:
# Define variables
x1, x2 = sym.symbols('x1 x2')
variaveis = [x1, x2]

# Define functions 
f1 = x1**2 + x2**2 - 4
f2 = x1**2 - x2**2- 1

F = np.transpose(np.array([f1,f2]))

# Define the values and jacabian matrix
## calculate values of F under a vector x
def calcF(F, x):
    Fx = []
    for f in F:
        Fx.append(f.subs([(x1,x[0]),(x2,x[1])]))
    return np.array(Fx)

## define jacobian matrix
def J(F):
    Jmatrix = []
    for f in F:
        Jmatrix.append([f.diff(x1), f.diff(x2)])
    return np.array(Jmatrix)


## calculate values of J under a vector x
def calcJ(J, x):
    Jx = []
    i = 0
    for linha in J:
        Jx.append([])
        for j in linha:
            Jx[i].append(j.subs([(x1,x[0]),(x2,x[1])]))
        i += 1
    return np.array(Jx)



## NOTE: the functions J(), calcJ() and calcF() could've been done in a more general way, such as to be used for any size of linear system
## adjusting automatically, but since we're just using this program for specific examples, for simplicity I used one for each example.
## Feel free to update it to work in a more general way.


In [111]:
# solve with Newton's method
x = np.transpose([1.5, 1.5]) # initial guess
n = 5 # number of equations and unknowns
tolerance = .01 # chosen - arbitrary because there's no real implication to have a specific tolerance defined
maxIterations = 20 # so it doesnt loop forever in case of failure

methodNewton(n, x, tolerance, maxIterations, F)


Começando com Xo =  [1.5 1.5]
1  Iteração x= [1.58333333 1.25      ] Norma:  0.2635231383473649
2  Iteração x= [1.58114035 1.225     ] Norma:  0.025095999124420895
3  Iteração x= [1.58113883 1.2247449 ] Norma:  0.000255106573881985


array([1.58113883, 1.2247449 ])

In [124]:
# solve with Broyden's method
x = np.transpose([1.5, 1.5]) # initial guess
n = 5 # number of equations and unknowns
tolerance = .01 # chosen - arbitrary because there's no real implication to have a specific tolerance defined
maxIterations = 20 # so it doesnt loop forever in case of failure

# methodBroyden(n, x, tolerance, maxIterations, F)

Ao = calcJ(J(F), x)
v = calcF(F, x)
A = np.transpose(Ao) # use gaussian elimination
s = -A * v
x = x + s
s

array([[-1.50000000000000, 3.00000000000000],
       [-1.50000000000000, -3.00000000000000]], dtype=object)

In [146]:
a = np.array([1,2])
b = np.transpose(a)
np.outer(a,b)

array([[1, 2],
       [2, 4]])

## ITEM 1

In [103]:
# define the functions
x1, x2, x3, x4, x5 = sym.symbols('x1 x2 x3 x4 x5')
R = [10, .193, 4.10622*10**(-4), 5.45177*10**(-4), 4.4975*10**(-7), 3.40735*10**(-5), 9.615*10**(-7)]

## define matrix F
f1 = x1*x2 +x1 -3*x5
f2 = 2*x1*x2 +x1 +3*R[-1]*(x2**2) +x2*(x3**2) +R[-4]*x2*x3 +R[-2]*x2*x4 +R[-3]*x2 -R[0]*x5
f3 = 2*x2*(x3**2) +R[-4]*x2*x3 + 2*R[-6]*(x3**2) +R[-5]*x3 -8*x5
f4 = R[-2]*x2*x4 +2*(x4**2) -4*R[0]*x5
f5 = x1*x2 +x1 +R[-1]*(x2**2) +x2*(x3**2) +R[-4]*x2*x3 +R[-2]*x2*x4 +R[-3]*x2 +R[-6]*(x3**2) +R[-5]*x3 +(x4**2) -1
    
F = np.transpose(np.array([f1,f2,f3,f4,f5]))

In [102]:
## calculate values of F under a vector x
def calcF(F, x):
    Fx = []
    for f in F:
        Fx.append(f.subs([(x1,x[0]),(x2,x[1]),(x3,x[2]),(x4,x[3]),(x5,x[4])]))
        
    return np.array(Fx)

## define jacobian matrix
def J(F):
    Jmatrix = []
    for f in F:
        Jmatrix.append([f.diff(x1), f.diff(x2), f.diff(x3), f.diff(x4), f.diff(x5)])
        
    return np.array(Jmatrix)    


## calculate values of J under a vector x
def calcJ(J, x):
    Jx = []
    i = 0
    for linha in J:
        Jx.append([])
        for j in linha:
            Jx[i].append(j.subs([(x1,x[0]),(x2,x[1]),(x3,x[2]),(x4,x[3]),(x5,x[4])]))
        
        i += 1
        
        
    return np.array(Jx)

## NOTE: the functions J(), calcJ() and calcF() could've been done in a more general way, such as to be used for any size of linear system
## adjusting automatically, but since we're just using this program for specific examples, for simplicity I used one for each example.
## Feel free to update it to work in a more general way.



### Método de Newton

In [73]:
# define method
def methodNewton(n, x, tolerance, maxIterations, F):
    output = "The method failed after "+str(maxIterations)+" iterations. The procedure was unsuccessful"
    
    k = 1
    print("Começando com Xo = ", x)
    while k <= maxIterations:
        Fx = [-x for x in calcF(F,x)]
        Jx = calcJ(J(F), x)
        y = np.linalg.solve(np.array(Jx, np.float64), np.array(Fx, np.float64))
        x = x + y
        print(k," Iteração x=", x, end=" ")
        if np.linalg.norm(y, np.inf)  < tolerance:
            output = x
            print("Norma: ", np.linalg.norm(x - (x-y)))
            break
        else:
            print("Norma: ", np.linalg.norm(x - (x-y)))
            k += 1
        
    return output

In [93]:
# solve with Newton's method

x = [10, 10, 10, 10, 10]
Xo = np.transpose(x) # initial approximation
n = 5 # number of equations and unknowns
tolerance = 10**(-5) # chosen - arbitrary because there's no real implication to have a specific tolerance defined
maxIterations = 20 # so it doesnt loop forever in case of failure

t0 = time.time() # measure time it takes to calculate
methodNewton(n, Xo, tolerance, maxIterations, F)
t1 = time.time() - t0
print(f"Tempo para calcular: {t1} segundos")


Começando com Xo =  [10 10 10 10 10]
1  Iteração x= [0.01065204 9.99922036 5.00102591 5.03641579 0.03645869] Norma:  15.769785630785213
2  Iteração x= [ 0.01001153 10.01012371  2.49920776  2.59112275  0.03674507] Norma:  3.498381268945265
3  Iteração x= [9.98373148e-03 1.00839478e+01 1.24338306e+00 1.43787284e+00
 3.68870704e-02] Norma:  1.7066139146402113
4  Iteração x= [9.68920699e-03 1.04317749e+01 6.06359646e-01 9.75892034e-01
 3.69557589e-02] Norma:  0.8603539169025427
5  Iteração x= [8.50591251e-03 1.18477258e+01 2.74174277e-01 8.66848855e-01
 3.69857062e-02] Norma:  1.4584772627650562
6  Iteração x= [5.41646124e-03 1.67133282e+01 1.03992448e-01 8.60022364e-01
 3.69918658e-02] Norma:  4.868583458334746
7  Iteração x= [2.92103470e-03 2.76408171e+01 6.02819450e-02 8.59724155e-01
 3.69765221e-02] Norma:  10.927576589262472
8  Iteração x= [3.45584277e-03 3.17170310e+01 6.96040198e-02 8.59516377e-01
 3.69616409e-02] Norma:  4.07622454194743
9  Iteração x= [3.43022114e-03 3.13294698e+0

### Método de Broyden

In [109]:
# define method
def methodBroyden(n, x, tolerance, maxIterations, F): # n is the number of equations and unknowns
    output = "The method failed after "+str(maxIterations)+" iterations. The procedure was unsuccessful"
    print("Começando com Xo = ", x)
    Ao = calcJ(J(F), x)
    v = calcF(F, x)
    A = np.transpose(Ao) # use gaussian elimination
    s = -A * v
    x = x + s
    k = 2
    
    
    while k <= maxIterations:
        w = v
        v = calcF(F, x)
        y = v - w
        z = -A* y
        p = -np.transpose(s) * z
        ut = np.transpose(np.transpose(s) * A)
        A = A + (1/p)*(s+z)*ut
        s = -A * v
        x = x + s
        print(k," Iteração x=", x, end=" ")
        if np.linalg.norm(s, np.inf) < tolerance:
            print("Norma: ", np.linalg.norm(x - (x-y)))
            output = x
            break
        print("Norma: ", np.linalg.norm(x - (x-y)))
        k += 1
        
    return output
             
    

In [108]:
# solve with Broyden's method

x = [10, 10, 10, 10, 10]
Xo = np.transpose(np.array(x)) # initial approximation
n = 5 # number of equations and unknowns
tolerance = 10**(-5) # chosen - arbitrary because there's no real implication to have a specific tolerance defined
maxIterations = 20 # so it doesnt loop forever in case of failure

t0 = time.time() # measure time it takes to calculate
methodBroyden(n, Xo, tolerance, maxIterations, F)
t1 = time.time() - t0
print(f"Tempo para calcular: {t1} segundos")

Começando com Xo =  [10 10 10 10 10]
2  Iteração x= [[(9680*(-11*x1*x2 - 11*x1 + 33*x5)/(-9680*x1*x2 - 9680*x1 + 29040*x5 + 774400) - 11)*(x1*x2 + x1 - 3*x5) - 870
  (233112.225779475*(-42*x1*x2 - 21*x1 - 6.05745e-5*x2**2 - 21*x2*x3**2 - 0.011448717*x2*x3 - 0.0007155435*x2*x4 - 9.44475e-6*x2 + 210*x5)/(-33600*x1*x2 - 16800*x1 - 0.0484596*x2**2 - 16800*x2*x3**2 - 9.1589736*x2*x3 - 0.5724348*x2*x4 - 0.0075558*x2 + 168000*x5 + 18648978.062358) - 21)*(2*x1*x2 + x1 + 2.8845e-6*x2**2 + x2*x3**2 + 0.000545177*x2*x3 + 3.40735e-5*x2*x4 + 4.4975e-7*x2 - 10*x5) - 23301.2225779475
  nan nan
  (-40535.9503532775*(-11*x1*x2 - 11*x1 - 1.05765e-5*x2**2 - 11*x2*x3**2 - 0.005996947*x2*x3 - 0.0003748085*x2*x4 - 4.94725e-6*x2 - 2.123*x3**2 - 0.004516842*x3 - 11*x4**2 + 11.0)/(2640*x1*x2 + 2640*x1 + 0.00253836*x2**2 + 2640*x2*x3**2 + 1.43926728*x2*x3 + 0.08995404*x2*x4 + 0.00118734*x2 + 509.52*x3**2 + 1.08404208*x3 + 2640*x4**2 - 3245516.0282622) - 11)*(x1*x2 + x1 + 9.615e-7*x2**2 + x2*x3**2 + 0.000545177*

TypeError: Invalid NaN comparison

### Comparação dos resultados

## ITEM 2

### Método de Newton

In [ ]:
Xo = np.transpose(x) # initial approximation
n = 5 # number of equations and unknowns
tolerance = .0005 # chosen
maxIterations = 100000 # so it doesnt loop forever in case of failure

def f(x):
    return


def methodNewton(p0, p1, tolerance, maxIterations):
    output = "The method failed after "+maxIterations+" iterations. The procedure was unsuccessful"
    
    i = 1
    q0 = f(p0)
    q1 = f(p1)
    while i <= maxIterations:
        p = p1 - q1*((p1-p0)/(q1-q0))
       
        if tolerance < p - p1 < tolerance:
            output = p
            break
        else:
            i += 1
            p0 = p1
            q0 = q1
            p1 = p
            q1 = f(p)
        
    return output

### Método de Broyden

In [ ]:
Po = x # initial approximation
tolerance = .0005 # arbitrary
maxIterations = 100000 # so it doesnt loop forever in case of failure
def f(x):
    return
def df(x):
    return
def J(x):
    result = df(x)
    return result
def F(x):
    return


def methodBroyden(n, x, tolerance, maxIterations): # n is the number of equations and unknowns
    output = "The method failed after "+maxIterations+" iterations. The procedure was unsuccessful"
    
    Ao = J(x)
    v = F(x)
    A = np.transpose(Ao) #use gaussian elimination
    s = -A * v
    x = x + s
    k = 2
    
    while k <= maxIterations:
        w = v
        v = F(x)
        y = v - w
        z = -A* y
        p = -np.transpose(s) * z
        ut = np.transpose(np.transpose(s) * A)
        A = A + (1/p)*(s+z)*ut
        s = -A * v
        x = x + s
        if np.linalg.norm(s) < tolerance:
            output = x
            break
        
        k += 1
        
    return output
          

### Comparação dos resultados

## ITEM 3

#### Bibliografia e referências: 

R.L. Burden & J.D. Faires, Numerical Analysis, Capítulos 2 e 10